apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-deployment
  labels:
    env: dev
spec:
  replicas: 3
  selector:
    matchLabels:
      env: dev
  template:
    metadata:
      labels:
        env: dev
    spec:
      containers:
      - name: node
        image: kubernetes/node:v1
        ports:
        - containerPort: 8080